name: Test passer
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Test-amazon-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run test
        env:
          CI: true
      - name: Check coverage threshold
        run: |
          coverage=$(cat coverage.json | jq -r '.total.lines.pct')
          if (( $(echo "$coverage < 90" | bc -l) )); then
            echo "Coverage is below 90%. Failing the build."
            exit 1
          fi
